[package]
name = "one_billion_row_challenge_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap2 = "0.9.3"
rayon = "1.5.1"
fast-float = "0.2"